import type { Store, User } from "./types";
export const users: User[] = [
  { id: "u1", name: "Ana Torres", role: "supervisor", status: "online" },
  { id: "u2", name: "Luis Rojas", role: "agente", status: "busy" },
  { id: "u3", name: "Mara Díaz", role: "agente", status: "online" },
];
export const seed: Store = {
  contacts: [
    {
      id: "c1",
      name: "Camila Vega",
      phone: "+51 912 440 381",
      email: "camila@atomo.pe",
      company: "Átomo Studio",
      tags: ["VIP", "Demo"],
      owner: "Ana Torres",
      consent: true,
    },
    {
      id: "c2",
      name: "Diego Luna",
      phone: "+51 955 201 044",
      email: "diego@norte.pe",
      company: "Norte Logística",
      tags: ["Empresa"],
      owner: "Luis Rojas",
      consent: true,
    },
    {
      id: "c3",
      name: "Sofía Paredes",
      phone: "+51 944 118 722",
      email: "sofia@verdemar.pe",
      company: "Verde Mar",
      tags: ["Nuevo"],
      owner: "Mara Díaz",
      consent: false,
      duplicate: true,
    },
    {
      id: "c4",
      name: "Mateo Silva",
      phone: "+51 987 051 221",
      email: "mateo@orbita.pe",
      company: "Órbita Labs",
      tags: ["Renovación"],
      owner: "Ana Torres",
      consent: true,
    },
  ],
  conversations: [
    {
      id: "v1",
      contactId: "c1",
      queue: "Ventas",
      status: "abierta",
      priority: "alta",
      assignee: "Ana Torres",
      unread: 2,
      sla: 8,
      aiMode: "Copiloto",
      tags: ["VIP"],
      messages: [
        {
          id: "m1",
          from: "contact",
          body: "Hola, quisiera cotizar el plan para mi equipo de 12 personas.",
          time: "09:42",
        },
        {
          id: "m2",
          from: "ai",
          body: "Borrador: Claro, Camila. Para 12 personas podemos preparar una propuesta. ¿Cuándo esperas iniciar?",
          time: "09:43",
        },
      ],
    },
    {
      id: "v2",
      contactId: "c2",
      queue: "Ventas",
      status: "esperando",
      priority: "media",
      assignee: "Luis Rojas",
      unread: 0,
      sla: 34,
      aiMode: "Humano",
      tags: ["Empresa"],
      messages: [
        {
          id: "m3",
          from: "agent",
          body: "Te envié el resumen de la propuesta. Quedo atento.",
          time: "Ayer",
        },
        {
          id: "m4",
          from: "contact",
          body: "Gracias, lo reviso con operaciones.",
          time: "Ayer",
        },
      ],
    },
    {
      id: "v3",
      contactId: "c3",
      queue: "Soporte",
      status: "abierta",
      priority: "alta",
      assignee: "Mara Díaz",
      unread: 1,
      sla: 4,
      aiMode: "Autopiloto",
      tags: ["Nuevo"],
      messages: [
        {
          id: "m5",
          from: "contact",
          body: "Necesito hablar con una persona sobre mi contrato.",
          time: "10:08",
        },
        {
          id: "m6",
          from: "ai",
          body: "He pausado la automatización y avisado al equipo.",
          time: "10:08",
        },
      ],
    },
    {
      id: "v4",
      contactId: "c4",
      queue: "Renovaciones",
      status: "resuelta",
      priority: "baja",
      assignee: "Ana Torres",
      unread: 0,
      sla: 120,
      aiMode: "Humano",
      tags: ["Renovación"],
      messages: [
        {
          id: "m7",
          from: "agent",
          body: "Renovación confirmada. Gracias por continuar con nosotros.",
          time: "Lun",
        },
      ],
    },
  ],
  deals: [
    {
      id: "d1",
      contactId: "c1",
      title: "Plan equipo Átomo",
      stage: "Calificado",
      value: 6800,
      probability: 55,
      next: "Demo · Hoy",
    },
    {
      id: "d2",
      contactId: "c2",
      title: "Operación Norte",
      stage: "Propuesta",
      value: 14200,
      probability: 70,
      next: "Seguimiento · Mañana",
    },
    {
      id: "d3",
      contactId: "c3",
      title: "Piloto Verde Mar",
      stage: "Nuevo",
      value: 3200,
      probability: 25,
      next: "Llamada · 27 ago",
    },
    {
      id: "d4",
      contactId: "c4",
      title: "Renovación anual",
      stage: "Ganado",
      value: 18400,
      probability: 100,
      next: "Onboarding · 30 ago",
    },
  ],
  automations: [
    {
      id: "a1",
      name: "Asignar leads de ventas",
      trigger: "Conversación creada",
      action: "Asignar a equipo Ventas",
      status: "Activa",
      runs: 128,
    },
    {
      id: "a2",
      name: "Seguimiento sin respuesta",
      trigger: "Sin respuesta por 24 h",
      action: "Crear tarea de seguimiento",
      status: "Pausada",
      runs: 42,
    },
  ],
  aiEnabled: true,
  emergency: false,
  aiPrompt:
    "Ayuda a resolver consultas comerciales con información verificada. Escala solicitudes sensibles.",
  confidence: 72,
};
